### ISSUE TITLE
"Error setting up entry OMIE for omie", 2024.4.0

### ISSUE THREAD

**Issue by RGarrido03** [luuuis/hass_omie#57]
Na versão 2024.4.0 beta (qualquer uma delas até ao momento, mas testado tanto com a b0 como com a b3), a integração da OMIE não inicia. O log reporta o seguinte erro:

```
2024-04-01 21:25:46.466 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry OMIE for omie
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 551, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/omie/__init__.py", line 33, in async_setup_entry
    spot = OMIEDailyCoordinator(hass,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/omie/coordinator.py", line 77, in __init__
    self._job.name,
    ^^^^^^^^^
AttributeError: 'OMIEDailyCoordinator' object has no attribute '_job'
```

**Comment by luuuis** [comment]
[v1.0.7](https://github.com/luuuis/hass_omie/releases/tag/v1.0.7) 👍
